name: 顽主の博客
description: 原创，没有烂大街的东西
meta_description: "WTF"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
# baseurl: http://fanyinan.me
domain_name: 'http://fanyinan.me'
google_analytics: 'UA-81807619-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://fanyinan.me'
author:         '顽主'
